//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ciribob.DCS.SimpleRadio.Standalone.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ciribob.DCS.SimpleRadio.Standalone.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban!.
        /// </summary>
        public static string ButtonBan {
            get {
                return ResourceManager.GetString("ButtonBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ButtonConfirm {
            get {
                return ResourceManager.GetString("ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISABLED.
        /// </summary>
        public static string ButtonDisabled {
            get {
                return ResourceManager.GetString("ButtonDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENABLED.
        /// </summary>
        public static string ButtonEnabled {
            get {
                return ResourceManager.GetString("ButtonEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        public static string ButtonKick {
            get {
                return ResourceManager.GetString("ButtonKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string ButtonMute {
            get {
                return ResourceManager.GetString("ButtonMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string ButtonOff {
            get {
                return ResourceManager.GetString("ButtonOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string ButtonOn {
            get {
                return ResourceManager.GetString("ButtonOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string ButtonStartingServer {
            get {
                return ResourceManager.GetString("ButtonStartingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Server.
        /// </summary>
        public static string ButtonStartServer {
            get {
                return ResourceManager.GetString("ButtonStartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        public static string ButtonStoppingServer {
            get {
                return ResourceManager.GetString("ButtonStoppingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Server.
        /// </summary>
        public static string ButtonStopServer {
            get {
                return ResourceManager.GetString("ButtonStopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Server IP.
        /// </summary>
        public static string LabelAdvancedServerIP {
            get {
                return ResourceManager.GetString("LabelAdvancedServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission Archive Time.
        /// </summary>
        public static string LabelArchiveTime {
            get {
                return ResourceManager.GetString("LabelArchiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for beta updates.
        /// </summary>
        public static string LabelCheckBetaUpdates {
            get {
                return ResourceManager.GetString("LabelCheckBetaUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client List Export File Path.
        /// </summary>
        public static string LabelClientExportFilePath {
            get {
                return ResourceManager.GetString("LabelClientExportFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients:.
        /// </summary>
        public static string LabelClients {
            get {
                return ResourceManager.GetString("LabelClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Limit.
        /// </summary>
        public static string LabelDistanceLimit {
            get {
                return ResourceManager.GetString("LabelDistanceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string LabelEnable {
            get {
                return ResourceManager.GetString("LabelEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Export List.
        /// </summary>
        public static string LabelExportList {
            get {
                return ResourceManager.GetString("LabelExportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Password.
        /// </summary>
        public static string LabelExternalAWACSBluePass {
            get {
                return ResourceManager.GetString("LabelExternalAWACSBluePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Password.
        /// </summary>
        public static string LabelExternalAWACSRedPass {
            get {
                return ResourceManager.GetString("LabelExternalAWACSRedPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATH.
        /// </summary>
        public static string LabelFilePath {
            get {
                return ResourceManager.GetString("LabelFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Lobby Freq. AM (MHz).
        /// </summary>
        public static string LabelGlobalLobbyFreq {
            get {
                return ResourceManager.GetString("LabelGlobalLobbyFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string LabelHttpApiEnable {
            get {
                return ResourceManager.GetString("LabelHttpApiEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string LabelHttpApiPort {
            get {
                return ResourceManager.GetString("LabelHttpApiPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of Sight.
        /// </summary>
        public static string LabelLOS {
            get {
                return ResourceManager.GetString("LabelLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotATC Transponder Export.
        /// </summary>
        public static string LabelLotATCExport {
            get {
                return ResourceManager.GetString("LabelLotATCExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotATC Transponder.
        /// </summary>
        public static string LabelLotATCTransponder {
            get {
                return ResourceManager.GetString("LabelLotATCTransponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Radio Effect on Global Freq.
        /// </summary>
        public static string LabelOverrideEffectsOnGlobal {
            get {
                return ResourceManager.GetString("LabelOverrideEffectsOnGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Radio Encryption.
        /// </summary>
        public static string LabelRadioEncryption {
            get {
                return ResourceManager.GetString("LabelRadioEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Expansion.
        /// </summary>
        public static string LabelRadioExpansion {
            get {
                return ResourceManager.GetString("LabelRadioExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRL Radio Rx Behaviour.
        /// </summary>
        public static string LabelRealRx {
            get {
                return ResourceManager.GetString("LabelRealRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRL Radio Tx Behaviour.
        /// </summary>
        public static string LabelRealTx {
            get {
                return ResourceManager.GetString("LabelRealTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retransmit Hop/Node Count.
        /// </summary>
        public static string LabelRetransmitNodeLimit {
            get {
                return ResourceManager.GetString("LabelRetransmitNodeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Coalition Radios.
        /// </summary>
        public static string LabelSecurity {
            get {
                return ResourceManager.GetString("LabelSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string LabelServerIP {
            get {
                return ResourceManager.GetString("LabelServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string LabelServerPort {
            get {
                return ResourceManager.GetString("LabelServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Channel Presets.
        /// </summary>
        public static string LabelServerPresetsEnabled {
            get {
                return ResourceManager.GetString("LabelServerPresetsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Presets Path.
        /// </summary>
        public static string LabelServerPresetsPath {
            get {
                return ResourceManager.GetString("LabelServerPresetsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Plug And Play (UPNP).
        /// </summary>
        public static string LabelServerUPNP {
            get {
                return ResourceManager.GetString("LabelServerUPNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Encryption.
        /// </summary>
        public static string LabelShowRadioEncryption {
            get {
                return ResourceManager.GetString("LabelShowRadioEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Transmitter Name.
        /// </summary>
        public static string LabelShowTransmitterName {
            get {
                return ResourceManager.GetString("LabelShowTransmitterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectator Audio.
        /// </summary>
        public static string LabelSpectator {
            get {
                return ResourceManager.GetString("LabelSpectator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict Radio Encryption.
        /// </summary>
        public static string LabelStrictEncryption {
            get {
                return ResourceManager.GetString("LabelStrictEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Admin.
        /// </summary>
        public static string LabelTabHeaderClientAdmin {
            get {
                return ResourceManager.GetString("LabelTabHeaderClientAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LabelTabHeaderSettings {
            get {
                return ResourceManager.GetString("LabelTabHeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Frequencies AM (MHz).
        /// </summary>
        public static string LabelTestFreq {
            get {
                return ResourceManager.GetString("LabelTestFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Received Transmissions.
        /// </summary>
        public static string LabelTransmissionLog {
            get {
                return ResourceManager.GetString("LabelTransmissionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tuned/Client Count.
        /// </summary>
        public static string LabelTunedCount {
            get {
                return ResourceManager.GetString("LabelTunedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MsgBoxUpdate1 {
            get {
                return ResourceManager.GetString("MsgBoxUpdate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string MsgBoxUpdate2 {
            get {
                return ResourceManager.GetString("MsgBoxUpdate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available!.
        /// </summary>
        public static string MsgBoxUpdate3 {
            get {
                return ResourceManager.GetString("MsgBoxUpdate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Auto update?
        ///    
        ///If DCS is running this will wait until DCS has stopped running and automatically update after as the SRS installer requires DCS to be stopped. 
        ///It will also close SRS automatically if DCS is no longer running.
        ///
        ///Yes - Auto Update (and wait for DCS to Close automatically)
        ///No - Manual Update
        ///Cancel - Ignore.
        /// </summary>
        public static string MsgBoxUpdate4 {
            get {
                return ResourceManager.GetString("MsgBoxUpdate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Auto Update - please download latest version manually.
        /// </summary>
        public static string MsgBoxUpdateFailed {
            get {
                return ResourceManager.GetString("MsgBoxUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update Error.
        /// </summary>
        public static string MsgBoxUpdateFailedTitle {
            get {
                return ResourceManager.GetString("MsgBoxUpdateFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string MsgBoxUpdateTitle {
            get {
                return ResourceManager.GetString("MsgBoxUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string PresenterLabelPort {
            get {
                return ResourceManager.GetString("PresenterLabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string PresenterLabelStatus {
            get {
                return ResourceManager.GetString("PresenterLabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings that only impact the radio simulation. Does not impact how the server program interacts with other programs..
        /// </summary>
        public static string SectionDescriptionRadioSimulation {
            get {
                return ResourceManager.GetString("SectionDescriptionRadioSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Settings.
        /// </summary>
        public static string SectionLabelProgram {
            get {
                return ResourceManager.GetString("SectionLabelProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Simulation Settings.
        /// </summary>
        public static string SectionLabelRadioSimulation {
            get {
                return ResourceManager.GetString("SectionLabelRadioSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Awacs Mode allows for users not inside of the DCS Game Server to connect and use radios like those in-game..
        /// </summary>
        public static string SubSectionDescriptionExternalAWACS {
            get {
                return ResourceManager.GetString("SubSectionDescriptionExternalAWACS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorum.
        /// </summary>
        public static string SubSectionDescriptionExternalProgramIntegrations {
            get {
                return ResourceManager.GetString("SubSectionDescriptionExternalProgramIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorum.
        /// </summary>
        public static string SubSectionDescriptionGeneral {
            get {
                return ResourceManager.GetString("SubSectionDescriptionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorum.
        /// </summary>
        public static string SubSectionDescriptionHttpApi {
            get {
                return ResourceManager.GetString("SubSectionDescriptionHttpApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorum.
        /// </summary>
        public static string SubSectionDescriptionNetwork {
            get {
                return ResourceManager.GetString("SubSectionDescriptionNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorum.
        /// </summary>
        public static string SubSectionDescriptionProgram {
            get {
                return ResourceManager.GetString("SubSectionDescriptionProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings that effect the feel and sound of radios..
        /// </summary>
        public static string SubSectionDescriptionRadioBehavior {
            get {
                return ResourceManager.GetString("SubSectionDescriptionRadioBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings that limit or enhance the simulated security of radios.
        /// </summary>
        public static string SubSectionDescriptionRadioSecurity {
            get {
                return ResourceManager.GetString("SubSectionDescriptionRadioSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External AWACS Mode (EAM).
        /// </summary>
        public static string SubSectionLabelExternalAWACS {
            get {
                return ResourceManager.GetString("SubSectionLabelExternalAWACS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Program Integrations.
        /// </summary>
        public static string SubSectionLabelExternalProgramIntegrations {
            get {
                return ResourceManager.GetString("SubSectionLabelExternalProgramIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string SubSectionLabelGeneral {
            get {
                return ResourceManager.GetString("SubSectionLabelGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP API Settings.
        /// </summary>
        public static string SubSectionLabelHttpApi {
            get {
                return ResourceManager.GetString("SubSectionLabelHttpApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Serttings.
        /// </summary>
        public static string SubSectionLabelNetwork {
            get {
                return ResourceManager.GetString("SubSectionLabelNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Behavior.
        /// </summary>
        public static string SubSectionLabelRadioBehavior {
            get {
                return ResourceManager.GetString("SubSectionLabelRadioBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Security.
        /// </summary>
        public static string SubSectionLabelRadioSecurity {
            get {
                return ResourceManager.GetString("SubSectionLabelRadioSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR Client List.
        /// </summary>
        public static string TitleClientList {
            get {
                return ResourceManager.GetString("TitleClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipArchiveTime {
            get {
                return ResourceManager.GetString("ToolTipArchiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipCheckForBetaUpdates {
            get {
                return ResourceManager.GetString("ToolTipCheckForBetaUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipClientExportFilePath {
            get {
                return ResourceManager.GetString("ToolTipClientExportFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipCoalitionSecurity {
            get {
                return ResourceManager.GetString("ToolTipCoalitionSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipDistanceLimit {
            get {
                return ResourceManager.GetString("ToolTipDistanceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipExportList {
            get {
                return ResourceManager.GetString("ToolTipExportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipExternalModeEnabled {
            get {
                return ResourceManager.GetString("ToolTipExternalModeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipExternalModePassBlue {
            get {
                return ResourceManager.GetString("ToolTipExternalModePassBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipExternalModePassRed {
            get {
                return ResourceManager.GetString("ToolTipExternalModePassRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipGlobalLobbyFrequencies {
            get {
                return ResourceManager.GetString("ToolTipGlobalLobbyFrequencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipHttpApiEnable {
            get {
                return ResourceManager.GetString("ToolTipHttpApiEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipHttpApiPort {
            get {
                return ResourceManager.GetString("ToolTipHttpApiPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipLOS {
            get {
                return ResourceManager.GetString("ToolTipLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipLotATCTransponder {
            get {
                return ResourceManager.GetString("ToolTipLotATCTransponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipOverrideEffectsOnGlobal {
            get {
                return ResourceManager.GetString("ToolTipOverrideEffectsOnGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipRadioEncryption {
            get {
                return ResourceManager.GetString("ToolTipRadioEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipRadioExpansion {
            get {
                return ResourceManager.GetString("ToolTipRadioExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipRealRx {
            get {
                return ResourceManager.GetString("ToolTipRealRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipRealTx {
            get {
                return ResourceManager.GetString("ToolTipRealTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipRetransmitNodeLimit {
            get {
                return ResourceManager.GetString("ToolTipRetransmitNodeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipServerIP {
            get {
                return ResourceManager.GetString("ToolTipServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipServerPort {
            get {
                return ResourceManager.GetString("ToolTipServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipServerPresetsEnabled {
            get {
                return ResourceManager.GetString("ToolTipServerPresetsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipServerPresetsPath {
            get {
                return ResourceManager.GetString("ToolTipServerPresetsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipServerUPNP {
            get {
                return ResourceManager.GetString("ToolTipServerUPNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipShowTransmitterName {
            get {
                return ResourceManager.GetString("ToolTipShowTransmitterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipShowTunedCount {
            get {
                return ResourceManager.GetString("ToolTipShowTunedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipSpectatorAudio {
            get {
                return ResourceManager.GetString("ToolTipSpectatorAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipStrictEncryption {
            get {
                return ResourceManager.GetString("ToolTipStrictEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipTestFreq {
            get {
                return ResourceManager.GetString("ToolTipTestFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToolTipTransmissionLog {
            get {
                return ResourceManager.GetString("ToolTipTransmissionLog", resourceCulture);
            }
        }
    }
}
