name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: msbuild /p:Configuration=Release /p:Platform=x64 /p:SourceLinkCreate=false

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: DCS-SimpleRadioStandalone
        path: install-build

    - name: Setup VSTest
      uses: Malcolmnixon/Setup-VSTest@v3

    - name: VSTest DCS-SR-CommonTests
      run: VSTest.Console DCS-SR-CommonTests\bin\x64\Release\DCS-SR-CommonTests.dll
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
