name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Tests
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'
        cache: true
    - run: dotnet restore
    - run: dotnet test --configuration Release --no-restore
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  publish:
    name: publish
    runs-on: windows-2025
    outputs:
      srs-install-zip: ${{ steps.upload.outputs.artifact-id }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        cache: true
    - run: dotnet restore
    - name: Publish
      run: ./publish.ps1 -NoSign
    - name: upload
      id: upload
      uses: actions/upload-artifact@v7
      with:
        name: DCS-SimpleRadioStandalone-${{ case(github.event_name == 'pull_request', github.head_ref, github.ref_name) }}-unsigned
        path: install-build
  sign:
    permissions:
      actions: read
      contents: read
    needs: publish
    name: Sign (Test)
    runs-on: ubuntu-latest
    steps:
    - name: submit signing request
      uses: signpath/github-action-submit-signing-request@v2
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: '${{ secrets.SIGNPATH_ORGANIZATION_ID }}'
        project-slug: 'DCS-SimpleRadioStandalone'
        signing-policy-slug: 'test-signing'
        artifact-configuration-slug: 'dotnet-srs-dll'
        github-artifact-id: '${{ needs.publish.outputs.srs-install-zip }}'
        wait-for-completion: true
        output-artifact-directory: signed
    - name: Upload (signed)
      uses: actions/upload-artifact@v7
      with:
        name: DCS-SimpleRadioStandalone-${{ case(github.event_name == 'pull_request', github.head_ref, github.ref_name) }}-signed.zip
        path: signed
