name: Release
on:
  push:
    tags:
      - '[0-9].[0-9].[0-9].[0-9]'
jobs:
  publish:
    name: publish
    runs-on: windows-2025
    outputs:
      srs-install-zip: ${{ steps.upload.outputs.artifact-id }}
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'
    - run: dotnet restore
    - name: Publish
      run: ./publish.ps1 -NoSign
    - name: Upload
      uses: actions/upload-artifact@v7
      id: upload
      with:
        name: DCS-SimpleRadioStandalone-${{ github.ref_name }}
        path: install-build
  sign:
    name: Sign (Release)
    permissions:
      actions: read
      contents: read
    needs: publish
    runs-on: ubuntu-latest
    environment: signing
    steps:
    - name: submit signing request
      uses: signpath/github-action-submit-signing-request@v2
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: '${{ secrets.SIGNPATH_ORGANIZATION_ID }}'
        project-slug: 'DCS-SimpleRadioStandalone'
        signing-policy-slug: 'release-signing'
        artifact-configuration-slug: 'dotnet-srs-dll'
        github-artifact-id: '${{ needs.publish.outputs.srs-install-zip }}'
        wait-for-completion: true
        output-artifact-directory: signed
    - name: Upload (signed)
      uses: actions/upload-artifact@v7
      with:
        name: DCS-SimpleRadioStandalone-${{ github.ref_name }}.zip
        path: signed
